# Use an official Node.js image as the base image
FROM node:20-alpine as development

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application code to the working directory
COPY . .

# Expose the port used by Next.js during development
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]
