// import Topbar from '@/components/Topbar';
// import { ThemeProvider } from "@mui/material";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import { useThemeContext } from "../components/theme/ThemeContextProvider";
import Container from '@/components/Container';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const { theme } = useThemeContext();

  return (
    <html lang="en">
      {/* <ThemeProvider theme={theme}> */}
        <body className={inter.className}>
          <Container>
            {children}
          </Container>
          {/* <Topbar /> */}
        </body>
      {/* </ThemeProvider> */}
    </html>
  )
}
