name: Repository contains a Backstage catalog file

on:
  pull_request:
    branches:
      - main

jobs:
  check-if-catalog-info-exists-and-is-valid:
    uses: loggi/github-workflows/.github/workflows/catalog-info-check.yaml@v1.6.1
    secrets: inherit
